// SessionRepository.swift
// ReSpeak
//
// Creates and manages exercise sessions and individual attempt records.
// No UIKit or SwiftUI imports — UI-free data layer only.

import Foundation
import Supabase

// MARK: - SessionRepository

/// Repository responsible for creating exercise sessions and logging attempts.
final class SessionRepository: Sendable {

    // MARK: Dependencies

    private let supabase: SupabaseService

    // MARK: Init

    init(supabase: SupabaseService = .shared) {
        self.supabase = supabase
    }

    // MARK: - Create Session

    /// Inserts a new `exercise_sessions` row and returns the created record.
    ///
    /// Call this when the user navigates into an exercise. The `started_at`
    /// timestamp is set by the database default (`now()`).
    ///
    /// - Parameters:
    ///   - exerciseId: The UUID of the exercise definition being practised.
    ///   - userId: The UUID of the authenticated user.
    /// - Returns: The newly created `ExerciseSession`.
    /// - Throws: `ReSpeakError.sessionCreateFailed` wrapping the underlying error.
    func createSession(exerciseId: UUID, userId: UUID) async throws -> ExerciseSession {
        do {
            struct Insert: Encodable {
                let user_id: String
                let exercise_definition_id: String
            }

            let payload = Insert(
                user_id: userId.uuidString,
                exercise_definition_id: exerciseId.uuidString
            )

            let session: ExerciseSession = try await supabase
                .from("exercise_sessions")
                .insert(payload)
                .select()
                .single()
                .execute()
                .value

            return session
        } catch {
            throw ReSpeakError.sessionCreateFailed(underlying: error)
        }
    }

    // MARK: - Log Attempt

    /// Inserts a new `exercise_attempts` row for a completed recording attempt.
    ///
    /// - Parameter attempt: A fully populated `ExerciseAttempt`. The `id`
    ///   field is generated by the database; provide a client-side UUID or
    ///   rely on `gen_random_uuid()` by omitting it from the insert payload.
    /// - Throws: `ReSpeakError.attemptLogFailed` wrapping the underlying error.
    func logAttempt(_ attempt: AttemptInsert) async throws -> ExerciseAttempt {
        do {
            let result: ExerciseAttempt = try await supabase
                .from("exercise_attempts")
                .insert(attempt)
                .select()
                .single()
                .execute()
                .value

            return result
        } catch {
            throw ReSpeakError.attemptLogFailed(underlying: error)
        }
    }

    // MARK: - Complete Session

    /// Stamps `completed_at` on an existing session row.
    ///
    /// - Parameter sessionId: The UUID of the session to mark complete.
    /// - Throws: `ReSpeakError.sessionCreateFailed` wrapping the underlying error.
    func completeSession(sessionId: UUID) async throws {
        do {
            struct Update: Encodable {
                let completed_at: String
            }

            let iso = ISO8601DateFormatter()
            let payload = Update(completed_at: iso.string(from: Date()))

            try await supabase
                .from("exercise_sessions")
                .update(payload)
                .eq("id", value: sessionId.uuidString)
                .execute()
        } catch {
            throw ReSpeakError.sessionCreateFailed(underlying: error)
        }
    }
}

// MARK: - AttemptInsert

/// Encodable insert payload for `exercise_attempts`.
/// Separate from `ExerciseAttempt` to exclude server-generated fields.
struct AttemptInsert: Encodable {
    let session_id: String
    let exercise_item_id: String
    var recording_url: String?
    var rating: Int?
}
