/**
 * generate-web.ts
 * ReSpeak3 BrandKit — Web (CSS + Tailwind) code generator
 *
 * Reads token JSON files from ../tokens/ and writes:
 *   - ../generated/web/theme.css      (CSS custom properties under :root)
 *   - ../generated/web/tailwind.tokens.ts  (Tailwind theme.extend object)
 *
 * Run:  npx ts-node scripts/generate-web.ts
 */

import * as fs from 'fs';
import * as path from 'path';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const TOKENS_DIR = path.resolve(__dirname, '..', 'tokens');
const OUTPUT_DIR = path.resolve(__dirname, '..', 'generated', 'web');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readJSON(filename: string): Record<string, unknown> {
  const fullPath = path.join(TOKENS_DIR, filename);
  const raw = fs.readFileSync(fullPath, 'utf-8');
  return JSON.parse(raw) as Record<string, unknown>;
}

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function write(filename: string, content: string): void {
  const fullPath = path.join(OUTPUT_DIR, filename);
  fs.writeFileSync(fullPath, content, 'utf-8');
  console.log(`  [web] wrote ${path.relative(path.resolve(__dirname, '..', '..'), fullPath)}`);
}

/** Convert a hex color to rgba() CSS value with an optional alpha. */
function hexToRgba(hex: string, alpha: number = 1): string {
  if (hex === 'transparent') return 'transparent';
  const cleaned = hex.replace('#', '');
  const r = parseInt(cleaned.slice(0, 2), 16);
  const g = parseInt(cleaned.slice(2, 4), 16);
  const b = parseInt(cleaned.slice(4, 6), 16);
  return alpha === 1 ? `rgb(${r} ${g} ${b})` : `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

// ---------------------------------------------------------------------------
// CSS Generator
// ---------------------------------------------------------------------------

function generateCSS(
  colors: Record<string, unknown>,
  typo: Record<string, unknown>,
  layout: Record<string, unknown>
): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * theme.css`);
  lines.push(` * ReSpeak3 BrandKit — HovaRehab design tokens as CSS custom properties.`);
  lines.push(` * Generated by brandkit/scripts/generate-web.ts`);
  lines.push(` * DO NOT EDIT MANUALLY — run \`npm run gen:web\` from /brandkit to regenerate.`);
  lines.push(` *`);
  lines.push(` * Import in your entry point:`);
  lines.push(` *   import './styles/theme.css'    // React / Vite`);
  lines.push(` *   @import './styles/theme.css';  // CSS`);
  lines.push(` */`);
  lines.push('');
  lines.push(':root {');

  // ------------------------------------------------------------------
  // Colors
  // ------------------------------------------------------------------
  lines.push('');
  lines.push('  /* ---- Brand Scale ---------------------------------------- */');
  const brand = colors['brand'] as Record<string, string>;
  for (const [k, v] of Object.entries(brand)) {
    lines.push(`  --color-brand-${k}: ${v};`);
  }

  lines.push('');
  lines.push('  /* ---- Surface Scale --------------------------------------- */');
  const surface = colors['surface'] as Record<string, string>;
  for (const [k, v] of Object.entries(surface)) {
    lines.push(`  --color-surface-${k}: ${v};`);
  }

  lines.push('');
  lines.push('  /* ---- Text Scale ------------------------------------------ */');
  const text = colors['text'] as Record<string, string>;
  for (const [k, v] of Object.entries(text)) {
    lines.push(`  --color-text-${k}: ${v};`);
  }

  lines.push('');
  lines.push('  /* ---- Semantic States ------------------------------------- */');
  const semantic = colors['semantic'] as Record<string, string>;
  for (const [k, v] of Object.entries(semantic)) {
    // camelCase key -> kebab-case CSS var
    const kebab = k.replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`  --color-semantic-${kebab}: ${v};`);
  }

  lines.push('');
  lines.push('  /* ---- Accent ---------------------------------------------- */');
  const accent = colors['accent'] as Record<string, string>;
  for (const [k, v] of Object.entries(accent)) {
    lines.push(`  --color-accent-${k}: ${v};`);
  }

  lines.push('');
  lines.push('  /* ---- Semantic Aliases (convenience) ---------------------- */');
  lines.push('  --color-primary:                 var(--color-brand-800);');
  lines.push('  --color-secondary:               var(--color-brand-500);');
  lines.push('  --color-accent:                  var(--color-accent-primary);');
  lines.push('  --color-background:              var(--color-surface-50);');
  lines.push('  --color-surface:                 var(--color-surface-0);');
  lines.push('  --color-surface-variant:         var(--color-surface-100);');
  lines.push('  --color-on-primary:              #FFFFFF;');
  lines.push('  --color-on-background:           var(--color-text-900);');
  lines.push('  --color-on-background-secondary: var(--color-text-500);');
  lines.push('  --color-error:                   var(--color-semantic-danger);');
  lines.push('  --color-success:                 var(--color-semantic-success);');
  lines.push('  --color-warning:                 var(--color-semantic-warning);');
  lines.push('  --color-info:                    var(--color-semantic-info);');
  lines.push('  --color-border:                  var(--color-surface-200);');
  lines.push('  --color-disabled:                var(--color-surface-300);');

  // ------------------------------------------------------------------
  // Typography
  // ------------------------------------------------------------------
  const sizes       = typo['size']       as Record<string, string>;
  const weights     = typo['weight']     as Record<string, string>;
  const lineHeights = typo['lineHeight'] as Record<string, string>;
  const letterSpacing = typo['letterSpacing'] as Record<string, string>;
  const fontFamily  = typo['fontFamily'] as Record<string, string>;

  lines.push('');
  lines.push('  /* ---- Font Families --------------------------------------- */');
  for (const [k, v] of Object.entries(fontFamily)) {
    lines.push(`  --font-family-${k}: ${v};`);
  }

  lines.push('');
  lines.push('  /* ---- Font Sizes (px) ------------------------------------- */');
  for (const [k, v] of Object.entries(sizes)) {
    lines.push(`  --typography-size-${k}: ${v}px;`);
  }

  lines.push('');
  lines.push('  /* ---- Font Weights ---------------------------------------- */');
  for (const [k, v] of Object.entries(weights)) {
    lines.push(`  --typography-weight-${k}: ${v};`);
  }

  lines.push('');
  lines.push('  /* ---- Line Heights ---------------------------------------- */');
  for (const [k, v] of Object.entries(lineHeights)) {
    lines.push(`  --typography-line-height-${k}: ${v};`);
  }

  lines.push('');
  lines.push('  /* ---- Letter Spacing ------------------------------------- */');
  for (const [k, v] of Object.entries(letterSpacing)) {
    lines.push(`  --typography-letter-spacing-${k}: ${v};`);
  }

  // ------------------------------------------------------------------
  // Layout — Spacing
  // ------------------------------------------------------------------
  const spacing  = layout['spacing']      as Record<string, string>;
  const radii    = layout['borderRadius'] as Record<string, string>;
  const borders  = layout['borderWidth']  as Record<string, string>;
  const shadows  = layout['shadow']       as Record<string, Record<string, string>>;

  lines.push('');
  lines.push('  /* ---- Spacing (px) ---------------------------------------- */');
  for (const [k, v] of Object.entries(spacing)) {
    lines.push(`  --layout-spacing-${k}: ${v}px;`);
  }

  lines.push('');
  lines.push('  /* ---- Border Radius (px) ---------------------------------- */');
  for (const [k, v] of Object.entries(radii)) {
    const cssVal = k === 'full' ? '9999px' : `${v}px`;
    lines.push(`  --layout-radius-${k}: ${cssVal};`);
  }

  lines.push('');
  lines.push('  /* ---- Border Width (px) ----------------------------------- */');
  for (const [k, v] of Object.entries(borders)) {
    lines.push(`  --layout-border-${k}: ${v}px;`);
  }

  lines.push('');
  lines.push('  /* ---- Box Shadows ----------------------------------------- */');
  for (const [level, spec] of Object.entries(shadows)) {
    if (spec['color'] === 'transparent') {
      lines.push(`  --shadow-${level}: none;`);
    } else {
      const rgba = hexToRgba(spec['color'], parseFloat(spec['opacity'] ?? '0.1'));
      lines.push(`  --shadow-${level}: ${spec['x']}px ${spec['y']}px ${spec['radius']}px 0px ${rgba};`);
    }
  }

  lines.push('');
  lines.push('  /* ---- Shadow Semantic Aliases ----------------------------- */');
  lines.push('  --shadow-card:     var(--shadow-sm);');
  lines.push('  --shadow-elevated: var(--shadow-md);');
  lines.push('  --shadow-floating: var(--shadow-lg);');
  lines.push('  --shadow-modal:    var(--shadow-xl);');

  lines.push('');
  lines.push('}');
  lines.push('');

  // Utility classes
  lines.push(`/* ================================================================`);
  lines.push(` * Utility classes using the token variables`);
  lines.push(` * Use these if you are NOT using Tailwind CSS.`);
  lines.push(` * ================================================================ */`);
  lines.push('');
  lines.push(`.bg-primary    { background-color: var(--color-primary); }`);
  lines.push(`.bg-secondary  { background-color: var(--color-secondary); }`);
  lines.push(`.bg-surface    { background-color: var(--color-surface); }`);
  lines.push(`.bg-background { background-color: var(--color-background); }`);
  lines.push('');
  lines.push(`.text-primary            { color: var(--color-primary); }`);
  lines.push(`.text-on-background      { color: var(--color-on-background); }`);
  lines.push(`.text-on-background-muted { color: var(--color-on-background-secondary); }`);
  lines.push(`.text-on-primary         { color: var(--color-on-primary); }`);
  lines.push('');
  lines.push(`.shadow-card     { box-shadow: var(--shadow-card); }`);
  lines.push(`.shadow-elevated { box-shadow: var(--shadow-elevated); }`);
  lines.push(`.shadow-floating { box-shadow: var(--shadow-floating); }`);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Tailwind Token Generator
// ---------------------------------------------------------------------------

function generateTailwind(
  colors: Record<string, unknown>,
  typo: Record<string, unknown>,
  layout: Record<string, unknown>
): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * tailwind.tokens.ts`);
  lines.push(` * ReSpeak3 BrandKit — Tailwind CSS theme.extend tokens.`);
  lines.push(` * Generated by brandkit/scripts/generate-web.ts`);
  lines.push(` * DO NOT EDIT MANUALLY — run \`npm run gen:web\` from /brandkit to regenerate.`);
  lines.push(` *`);
  lines.push(` * Usage in tailwind.config.ts:`);
  lines.push(` *   import { tokens } from '../brandkit/generated/web/tailwind.tokens'`);
  lines.push(` *   export default { theme: { extend: { ...tokens } } }`);
  lines.push(` */`);
  lines.push('');

  const brand   = colors['brand']   as Record<string, string>;
  const surface = colors['surface'] as Record<string, string>;
  const text    = colors['text']    as Record<string, string>;
  const semantic = colors['semantic'] as Record<string, string>;
  const accent  = colors['accent']  as Record<string, string>;

  const sizes       = typo['size']       as Record<string, string>;
  const weights     = typo['weight']     as Record<string, string>;
  const lineHeights = typo['lineHeight'] as Record<string, string>;
  const fontFamily  = typo['fontFamily'] as Record<string, string>;

  const spacing = layout['spacing']      as Record<string, string>;
  const radii   = layout['borderRadius'] as Record<string, string>;
  const borders = layout['borderWidth']  as Record<string, string>;
  const shadows = layout['shadow']       as Record<string, Record<string, string>>;

  lines.push(`export const tokens = {`);

  // ---- Colors ----
  lines.push(`  colors: {`);
  lines.push(`    brand: {`);
  for (const [k, v] of Object.entries(brand)) {
    lines.push(`      '${k}': '${v}',`);
  }
  lines.push(`    },`);

  lines.push(`    surface: {`);
  for (const [k, v] of Object.entries(surface)) {
    lines.push(`      '${k}': '${v}',`);
  }
  lines.push(`    },`);

  lines.push(`    text: {`);
  for (const [k, v] of Object.entries(text)) {
    lines.push(`      '${k}': '${v}',`);
  }
  lines.push(`    },`);

  lines.push(`    semantic: {`);
  for (const [k, v] of Object.entries(semantic)) {
    lines.push(`      '${k}': '${v}',`);
  }
  lines.push(`    },`);

  lines.push(`    accent: {`);
  for (const [k, v] of Object.entries(accent)) {
    lines.push(`      '${k}': '${v}',`);
  }
  lines.push(`    },`);

  // Semantic convenience aliases as top-level Tailwind color names
  lines.push(`    // Convenience semantic aliases`);
  lines.push(`    primary:               'var(--color-primary)',`);
  lines.push(`    secondary:             'var(--color-secondary)',`);
  lines.push(`    background:            'var(--color-background)',`);
  lines.push(`    'on-primary':          'var(--color-on-primary)',`);
  lines.push(`    'on-background':       'var(--color-on-background)',`);
  lines.push(`    error:                 'var(--color-error)',`);
  lines.push(`    success:               'var(--color-success)',`);
  lines.push(`    warning:               'var(--color-warning)',`);
  lines.push(`    info:                  'var(--color-info)',`);
  lines.push(`    border:                'var(--color-border)',`);
  lines.push(`    disabled:              'var(--color-disabled)',`);
  lines.push(`  },`);

  // ---- Font Size ----
  lines.push(`  fontSize: {`);
  for (const [k, v] of Object.entries(sizes)) {
    lines.push(`    '${k}': '${v}px',`);
  }
  lines.push(`  },`);

  // ---- Font Weight ----
  lines.push(`  fontWeight: {`);
  for (const [k, v] of Object.entries(weights)) {
    lines.push(`    '${k}': '${v}',`);
  }
  lines.push(`  },`);

  // ---- Font Family ----
  lines.push(`  fontFamily: {`);
  for (const [k, v] of Object.entries(fontFamily)) {
    // Use double quotes for the value to avoid conflicts with single-quoted font names
    lines.push(`    '${k}': "${v}",`);
  }
  lines.push(`  },`);

  // ---- Line Height ----
  lines.push(`  lineHeight: {`);
  for (const [k, v] of Object.entries(lineHeights)) {
    lines.push(`    '${k}': '${v}',`);
  }
  lines.push(`  },`);

  // ---- Spacing ----
  lines.push(`  spacing: {`);
  for (const [k, v] of Object.entries(spacing)) {
    lines.push(`    '${k}': '${v}px',`);
  }
  lines.push(`  },`);

  // ---- Border Radius ----
  lines.push(`  borderRadius: {`);
  for (const [k, v] of Object.entries(radii)) {
    const cssVal = k === 'full' ? '9999px' : `${v}px`;
    lines.push(`    '${k}': '${cssVal}',`);
  }
  lines.push(`  },`);

  // ---- Border Width ----
  lines.push(`  borderWidth: {`);
  for (const [k, v] of Object.entries(borders)) {
    lines.push(`    '${k}': '${v}px',`);
  }
  lines.push(`  },`);

  // ---- Box Shadow ----
  lines.push(`  boxShadow: {`);
  for (const [level, spec] of Object.entries(shadows)) {
    if (spec['color'] === 'transparent') {
      lines.push(`    '${level}': 'none',`);
    } else {
      const rgba = hexToRgba(spec['color'], parseFloat(spec['opacity'] ?? '0.1'));
      lines.push(`    '${level}': '${spec['x']}px ${spec['y']}px ${spec['radius']}px 0px ${rgba}',`);
    }
  }
  lines.push(`    // Semantic aliases`);
  lines.push(`    'card':     'var(--shadow-card)',`);
  lines.push(`    'elevated': 'var(--shadow-elevated)',`);
  lines.push(`    'floating': 'var(--shadow-floating)',`);
  lines.push(`    'modal':    'var(--shadow-modal)',`);
  lines.push(`  },`);

  lines.push(`} as const;`);
  lines.push('');
  lines.push(`export type Tokens = typeof tokens;`);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  console.log('ReSpeak3 BrandKit — Web generator');
  console.log('----------------------------------');

  ensureDir(OUTPUT_DIR);

  const colors = readJSON('colors.json');
  const typo   = readJSON('typography.json');
  const layout = readJSON('layout.json');

  write('theme.css',           generateCSS(colors, typo, layout));
  write('tailwind.tokens.ts',  generateTailwind(colors, typo, layout));

  console.log('\nDone. See /brandkit/generated/web/ for output files.\n');
}

main();
