/**
 * generate-ios.ts
 * ReSpeak3 BrandKit — iOS/SwiftUI code generator
 *
 * Reads token JSON files from ../tokens/ and writes three Swift source files
 * to ../generated/ios/:
 *   - BrandColors.swift
 *   - BrandTypography.swift
 *   - BrandLayout.swift
 *
 * Run:  npx ts-node scripts/generate-ios.ts
 */

import * as fs from 'fs';
import * as path from 'path';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const TOKENS_DIR  = path.resolve(__dirname, '..', 'tokens');
const OUTPUT_DIR  = path.resolve(__dirname, '..', 'generated', 'ios');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readJSON(filename: string): Record<string, unknown> {
  const fullPath = path.join(TOKENS_DIR, filename);
  const raw = fs.readFileSync(fullPath, 'utf-8');
  return JSON.parse(raw) as Record<string, unknown>;
}

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function write(filename: string, content: string): void {
  const fullPath = path.join(OUTPUT_DIR, filename);
  fs.writeFileSync(fullPath, content, 'utf-8');
  console.log(`  [ios] wrote ${path.relative(path.resolve(__dirname, '..', '..'), fullPath)}`);
}

/** Convert a 6-digit hex string to Swift Color(red:green:blue:) components. */
function hexToSwiftRGB(hex: string): string {
  const cleaned = hex.replace('#', '');
  const r = parseInt(cleaned.slice(0, 2), 16) / 255;
  const g = parseInt(cleaned.slice(2, 4), 16) / 255;
  const b = parseInt(cleaned.slice(4, 6), 16) / 255;
  return `Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`;
}

/** Swift-safe property name: "2xl" -> "size2XL", "900" -> "n900" etc. */
function toSwiftName(key: string, prefix: string = ''): string {
  // Numeric-only keys get a letter prefix to be valid Swift identifiers
  const safe = key.replace(/^(\d)/, '_$1');
  // kebab/dot to camelCase
  const camel = safe.replace(/[-.](\w)/g, (_, c: string) => c.toUpperCase());
  return prefix ? `${prefix}${camel.charAt(0).toUpperCase()}${camel.slice(1)}` : camel;
}

function header(filename: string, description: string, usageLines: string[]): string {
  const usageBlock = usageLines.map(l => ` //   ${l}`).join('\n');
  return `// ${filename}
// ReSpeak — generated by brandkit/scripts/generate-ios.ts
// DO NOT EDIT MANUALLY — run \`npm run gen:ios\` from /brandkit to regenerate.
//
// ${description}
//
// Usage:
${usageBlock}

import SwiftUI

`;
}

// ---------------------------------------------------------------------------
// BrandColors.swift
// ---------------------------------------------------------------------------

function generateColors(colors: Record<string, unknown>): string {
  const lines: string[] = [];

  lines.push(header(
    'BrandColors.swift',
    'Color tokens for the HovaRehab / ReSpeak3 design system.',
    [
      'Text("Hello").foregroundStyle(BrandColors.brand800)',
      'Rectangle().fill(BrandColors.semanticSuccess)',
      'Color.brand800   // Color extension shorthand',
    ]
  ));

  // --- Color(hex:) helper extension ---
  lines.push(`// MARK: - Color(hex:) Helper`);
  lines.push(`
extension Color {
    /// Initialise a SwiftUI Color from a 6-digit hex string (e.g. "#1A3C5E").
    /// Alpha defaults to 1.0 (fully opaque).
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let r = Double((int >> 16) & 0xFF) / 255.0
        let g = Double((int >> 8)  & 0xFF) / 255.0
        let b = Double( int        & 0xFF) / 255.0
        self.init(red: r, green: g, blue: b)
    }
}
`);

  // --- BrandColors enum ---
  lines.push(`// MARK: - BrandColors\n`);
  lines.push(`/// All design-system color tokens, generated from brandkit/tokens/colors.json.`);
  lines.push(`public enum BrandColors {\n`);

  function emitGroup(groupKey: string, values: Record<string, string>, sectionComment: string): void {
    lines.push(`    // MARK: - ${sectionComment}\n`);
    for (const [tokenKey, hex] of Object.entries(values)) {
      if (hex === 'transparent') {
        const propName = toSwiftName(`${groupKey}${tokenKey.charAt(0).toUpperCase()}${tokenKey.slice(1)}`);
        lines.push(`    /// Fully transparent — use for no-fill / clear backgrounds.`);
        lines.push(`    public static let ${propName}: Color = .clear`);
      } else {
        const propName = toSwiftName(`${groupKey}${tokenKey.charAt(0).toUpperCase()}${tokenKey.slice(1)}`);
        lines.push(`    public static let ${propName}: Color = ${hexToSwiftRGB(hex)}  // ${hex}`);
      }
    }
    lines.push('');
  }

  const brand   = colors['brand']   as Record<string, string>;
  const surface = colors['surface'] as Record<string, string>;
  const text    = colors['text']    as Record<string, string>;
  const semantic = colors['semantic'] as Record<string, string>;
  const accent  = colors['accent']  as Record<string, string>;
  const fixed   = colors['fixed']   as Record<string, string>;

  emitGroup('brand',   brand,   'Brand Scale — brand.50 → brand.900');
  emitGroup('surface', surface, 'Surface Scale — surface.0 → surface.300');
  emitGroup('text',    text,    'Text Scale — text.300 → text.900');

  // Semantic with light variants grouped
  lines.push(`    // MARK: - Semantic States\n`);
  for (const [tokenKey, hex] of Object.entries(semantic)) {
    const propName = `semantic${tokenKey.charAt(0).toUpperCase()}${tokenKey.slice(1)}`;
    lines.push(`    public static let ${propName}: Color = ${hexToSwiftRGB(hex)}  // ${hex}`);
  }
  lines.push('');

  emitGroup('accent', accent, 'Accent');
  emitGroup('fixed',  fixed,  'Fixed (White / Black / Transparent)');

  // Semantic convenience aliases matching original BrandColors API
  lines.push(`    // MARK: - Semantic Convenience Aliases (matches pre-existing BrandColors API)\n`);
  lines.push(`    /// Main brand / primary interactive color.`);
  lines.push(`    public static let primary:               Color = brand800`);
  lines.push(`    /// Supporting brand color.`);
  lines.push(`    public static let secondary:             Color = brand500`);
  lines.push(`    /// Teal accent / CTA highlight.`);
  lines.push(`    public static let accent:                Color = accentPrimary`);
  lines.push(`    /// Root page background.`);
  lines.push(`    public static let background:            Color = surface50`);
  lines.push(`    /// Card / panel surface.`);
  lines.push(`    public static let surface:               Color = surface0`);
  lines.push(`    /// Slightly tinted alternate surface.`);
  lines.push(`    public static let surfaceVariant:        Color = surface100`);
  lines.push(`    /// Text / icon on primary-colored backgrounds.`);
  lines.push(`    public static let onPrimary:             Color = fixedWhite`);
  lines.push(`    /// Primary text on light backgrounds.`);
  lines.push(`    public static let onBackground:          Color = text900`);
  lines.push(`    /// Secondary / muted text.`);
  lines.push(`    public static let onBackgroundSecondary: Color = text500`);
  lines.push(`    /// Error / destructive state.`);
  lines.push(`    public static let error:                 Color = semanticDanger`);
  lines.push(`    /// Success state.`);
  lines.push(`    public static let success:               Color = semanticSuccess`);
  lines.push(`    /// Warning state.`);
  lines.push(`    public static let warning:               Color = semanticWarning`);
  lines.push(`    /// Informational state.`);
  lines.push(`    public static let info:                  Color = semanticInfo`);
  lines.push(`    /// Subtle border and separator color.`);
  lines.push(`    public static let border:                Color = surface200`);
  lines.push(`    /// Disabled text and control color.`);
  lines.push(`    public static let disabled:              Color = surface300`);
  lines.push(`}`);
  lines.push('');

  // --- Color extension shortcuts ---
  lines.push(`// MARK: - Color Static Shorthand Extensions\n`);
  lines.push(`/// Provides \`Color.brand800\`, \`Color.semanticSuccess\` etc. shorthand.`);
  lines.push(`public extension Color {`);
  const allGroups: [string, Record<string, string>][] = [
    ['brand', brand], ['surface', surface], ['text', text], ['accent', accent], ['fixed', fixed],
  ];
  for (const [groupKey, values] of allGroups) {
    for (const tokenKey of Object.keys(values)) {
      const propName = toSwiftName(`${groupKey}${tokenKey.charAt(0).toUpperCase()}${tokenKey.slice(1)}`);
      lines.push(`    static var ${propName}: Color { BrandColors.${propName} }`);
    }
  }
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// BrandTypography.swift
// ---------------------------------------------------------------------------

function generateTypography(typo: Record<string, unknown>): string {
  const lines: string[] = [];

  lines.push(header(
    'BrandTypography.swift',
    'Typography tokens for the HovaRehab / ReSpeak3 design system.',
    [
      'Text("Welcome").font(BrandTypography.display)',
      'Text("Section").font(BrandTypography.headline)',
      'Text("Details").brandStyle(.body)',
    ]
  ));

  const sizes       = typo['size']       as Record<string, string>;
  const weights     = typo['weight']     as Record<string, string>;
  const lineHeights = typo['lineHeight'] as Record<string, string>;
  const roles       = typo['roles']      as Record<string, Record<string, string>>;

  // Map token size keys to CGFloat names
  const sizeMap: Record<string, string> = {};
  for (const [k, v] of Object.entries(sizes)) {
    sizeMap[k] = v;
  }

  // Map weight strings to SwiftUI Font.Weight
  const weightMap: Record<string, string> = {
    '400': '.regular',
    '500': '.medium',
    '600': '.semibold',
    '700': '.bold',
  };

  lines.push(`// MARK: - BrandTypography\n`);
  lines.push(`/// Typographic scale for the ReSpeak / HovaRehab design system.`);
  lines.push(`/// All fonts use the system default (SF Pro) for Dynamic Type compatibility.`);
  lines.push(`public enum BrandTypography {\n`);

  lines.push(`    // MARK: - Semantic Role Fonts\n`);
  for (const [roleName, roleSpec] of Object.entries(roles)) {
    const sizePt  = sizeMap[roleSpec['size']] ?? '17';
    const weightW = weights[roleSpec['weight']] ?? '400';
    const weight  = weightMap[weightW] ?? '.regular';
    const desc    = roleSpec['description'] ?? '';
    const swiftName = roleName; // already camelCase in JSON

    lines.push(`    /// ${desc}`);
    lines.push(`    public static let ${swiftName}: Font = .system(size: ${sizePt}, weight: ${weight}, design: .default)`);
  }
  lines.push('');

  lines.push(`    // MARK: - Raw Size Scale\n`);
  for (const [k, v] of Object.entries(sizes)) {
    const safe = k.replace(/^(\d)/, '_$1');
    lines.push(`    /// ${v}pt`);
    lines.push(`    public static let size${safe.charAt(0).toUpperCase()}${safe.slice(1)}: CGFloat = ${v}`);
  }
  lines.push('');

  lines.push(`    // MARK: - Raw Weight Scale\n`);
  for (const [k, v] of Object.entries(weights)) {
    const swiftW = weightMap[v] ?? '.regular';
    lines.push(`    public static let weight${k.charAt(0).toUpperCase()}${k.slice(1)}: Font.Weight = ${swiftW}`);
  }
  lines.push('');

  // Convenience aliases to match legacy BrandTypography API
  lines.push(`    // MARK: - Legacy API Aliases (matches pre-existing BrandTypography)\n`);
  const legacyMap: [string, string][] = [
    ['largeTitle',  'display'],
    ['title1',      'title'],
    ['title2',      'subtitle'],
    ['title3',      'sectionTitle'],
    ['callout',     'callout'],
    ['subheadline', 'subheadline'],
    ['footnote',    'caption'],
    ['caption1',    'label'],
    ['caption2',    'label'],
    ['navTitle',    'navTitle'],
  ];
  for (const [alias, role] of legacyMap) {
    if (alias !== role) {
      lines.push(`    public static let ${alias}: Font = ${role}`);
    }
  }
  lines.push(`}`);
  lines.push('');

  // BrandTextStyle enum + modifier (preserve full API from existing file)
  lines.push(`// MARK: - BrandTextStyle\n`);
  lines.push(`/// Semantic text style pairings combining a font and its standard foreground color.`);
  lines.push(`public enum BrandTextStyle {`);
  const styleNames = [
    'display', 'title', 'subtitle', 'sectionTitle', 'headline',
    'body', 'callout', 'subheadline', 'caption', 'label',
    'button', 'navTitle', 'onPrimary',
  ];
  for (const s of styleNames) {
    lines.push(`    case ${s}`);
  }
  lines.push(`}`);
  lines.push('');

  lines.push(`// MARK: - BrandTextStyleModifier\n`);
  lines.push(`private struct BrandTextStyleModifier: ViewModifier {`);
  lines.push(`    let style: BrandTextStyle\n`);
  lines.push(`    func body(content: Content) -> some View {`);
  lines.push(`        switch style {`);

  const styleSpecs: Record<string, { font: string; color: string }> = {
    display:      { font: 'BrandTypography.display',      color: 'BrandColors.onBackground' },
    title:        { font: 'BrandTypography.title',        color: 'BrandColors.onBackground' },
    subtitle:     { font: 'BrandTypography.subtitle',     color: 'BrandColors.onBackground' },
    sectionTitle: { font: 'BrandTypography.sectionTitle', color: 'BrandColors.onBackground' },
    headline:     { font: 'BrandTypography.headline',     color: 'BrandColors.onBackground' },
    body:         { font: 'BrandTypography.body',         color: 'BrandColors.onBackground' },
    callout:      { font: 'BrandTypography.callout',      color: 'BrandColors.onBackgroundSecondary' },
    subheadline:  { font: 'BrandTypography.subheadline',  color: 'BrandColors.onBackgroundSecondary' },
    caption:      { font: 'BrandTypography.caption',      color: 'BrandColors.onBackgroundSecondary' },
    label:        { font: 'BrandTypography.label',        color: 'BrandColors.onBackgroundSecondary' },
    button:       { font: 'BrandTypography.button',       color: 'BrandColors.onBackground' },
    navTitle:     { font: 'BrandTypography.navTitle',     color: 'BrandColors.onBackground' },
    onPrimary:    { font: 'BrandTypography.body',         color: 'BrandColors.onPrimary' },
  };

  for (const [caseName, spec] of Object.entries(styleSpecs)) {
    lines.push(`        case .${caseName}:`);
    lines.push(`            content`);
    lines.push(`                .font(${spec.font})`);
    lines.push(`                .foregroundStyle(${spec.color})`);
  }
  lines.push(`        }`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push('');

  lines.push(`// MARK: - View Extension\n`);
  lines.push(`public extension View {`);
  lines.push(`    /// Applies a semantic brand text style (font + foreground color pairing).`);
  lines.push(`    ///`);
  lines.push(`    /// Example:`);
  lines.push(`    /// \`\`\`swift`);
  lines.push(`    /// Text("Hello").brandStyle(.headline)`);
  lines.push(`    /// \`\`\``);
  lines.push(`    func brandStyle(_ style: BrandTextStyle) -> some View {`);
  lines.push(`        self.modifier(BrandTextStyleModifier(style: style))`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// BrandLayout.swift
// ---------------------------------------------------------------------------

function generateLayout(layout: Record<string, unknown>): string {
  const lines: string[] = [];

  lines.push(header(
    'BrandLayout.swift',
    'Spacing, border radius, shadow, and border tokens for the HovaRehab / ReSpeak3 design system.',
    [
      '.padding(Spacing.lg)                      // 16 pt',
      'VStack(spacing: Spacing.xl) { ... }       // 24 pt',
      '.clipShape(RoundedRectangle(cornerRadius: Radii.card))',
      '.cardShadow()  // view modifier shorthand',
    ]
  ));

  const spacing      = layout['spacing']          as Record<string, string>;
  const spAliases    = layout['spacingAliases']   as Record<string, string>;
  const radii        = layout['borderRadius']     as Record<string, string>;
  const radiiAliases = layout['borderRadiusAliases'] as Record<string, string>;
  const borders      = layout['borderWidth']      as Record<string, string>;
  const shadows      = layout['shadow']           as Record<string, Record<string, string>>;
  const shadAliases  = layout['shadowAliases']    as Record<string, string>;

  // --- Spacing ---
  lines.push(`// MARK: - Spacing\n`);
  lines.push(`/// Spacing scale for the ReSpeak / HovaRehab design system.`);
  lines.push(`/// Based on a 4-pt base unit to align with iOS HIG recommendations.`);
  lines.push(`public enum Spacing {\n`);
  for (const [k, v] of Object.entries(spacing)) {
    // Convert "2xl" -> "xxl" style for Swift (avoid leading-digit identifiers)
    const swiftKey = k.replace(/^(\d+)xl$/, (_, n: string) => 'x'.repeat(parseInt(n, 10)) + 'l');
    lines.push(`    /// ${v} pt`);
    lines.push(`    public static let ${swiftKey}: CGFloat = ${v}`);
  }
  lines.push('');
  lines.push(`    // MARK: Semantic Aliases\n`);
  for (const [alias, ref] of Object.entries(spAliases)) {
    const swiftRef = ref.replace(/^(\d+)xl$/, (_, n: string) => 'x'.repeat(parseInt(n, 10)) + 'l');
    lines.push(`    public static let ${alias}: CGFloat = ${swiftRef}`);
  }
  lines.push(`}`);
  lines.push('');

  // --- Radii ---
  lines.push(`// MARK: - Radii\n`);
  lines.push(`/// Corner radius tokens for the ReSpeak / HovaRehab design system.`);
  lines.push(`public enum Radii {\n`);
  for (const [k, v] of Object.entries(radii)) {
    const swiftKey = k.replace(/^(\d+)xl$/, (_, n: string) => 'x'.repeat(parseInt(n, 10)) + 'l');
    lines.push(`    /// ${v} pt`);
    lines.push(`    public static let ${swiftKey}: CGFloat = ${v}`);
  }
  lines.push('');
  lines.push(`    // MARK: Semantic Aliases\n`);
  for (const [alias, ref] of Object.entries(radiiAliases)) {
    const swiftRef = ref.replace(/^(\d+)xl$/, (_, n: string) => 'x'.repeat(parseInt(n, 10)) + 'l');
    lines.push(`    public static let ${alias}: CGFloat = ${swiftRef}`);
  }
  lines.push(`}`);
  lines.push('');

  // --- BorderWidth ---
  lines.push(`// MARK: - BorderWidth\n`);
  lines.push(`/// Border / stroke width tokens.`);
  lines.push(`public enum BorderWidth {\n`);
  for (const [k, v] of Object.entries(borders)) {
    // 'default' is a Swift keyword — escape it with backticks
    const swiftKey = k === 'default' ? '`default`' : k;
    lines.push(`    /// ${v} pt`);
    lines.push(`    public static let ${swiftKey}: CGFloat = ${v}`);
  }
  lines.push(`}`);
  lines.push('');

  // --- Shadows (struct approach for grouping) ---
  lines.push(`// MARK: - Shadows\n`);
  lines.push(`/// Shadow elevation tokens. Each level groups color, radius, x, y, and opacity.`);
  lines.push(`public enum Shadows {\n`);
  lines.push(`    public struct ShadowToken {`);
  lines.push(`        public let color: Color`);
  lines.push(`        public let radius: CGFloat`);
  lines.push(`        public let x: CGFloat`);
  lines.push(`        public let y: CGFloat`);
  lines.push(`    }\n`);

  for (const [level, spec] of Object.entries(shadows)) {
    const swiftKey = level.replace(/^(\d+)xl$/, (_, n) => 'x'.repeat(parseInt(n, 10)) + 'l');
    if (spec['color'] === 'transparent') {
      lines.push(`    public static let ${swiftKey}: ShadowToken = ShadowToken(`);
      lines.push(`        color: .clear, radius: 0, x: 0, y: 0`);
      lines.push(`    )`);
    } else {
      const opacity = parseFloat(spec['opacity'] ?? '0.10');
      lines.push(`    public static let ${swiftKey}: ShadowToken = ShadowToken(`);
      lines.push(`        color: ${hexToSwiftRGB(spec['color'])}.opacity(${opacity}),`);
      lines.push(`        radius: ${spec['radius']}, x: ${spec['x']}, y: ${spec['y']}`);
      lines.push(`    )`);
    }
    lines.push('');
  }

  lines.push(`    // MARK: Semantic Aliases\n`);
  for (const [alias, ref] of Object.entries(shadAliases)) {
    const swiftRef = ref.replace(/^(\d+)xl$/, (_, n: string) => 'x'.repeat(parseInt(n, 10)) + 'l');
    lines.push(`    public static let ${alias}: ShadowToken = ${swiftRef}`);
  }
  lines.push('');

  // Legacy flat property aliases (matches Shadows.cardColor pattern)
  lines.push(`    // MARK: Legacy Flat Property Aliases (matches pre-existing Shadows API)\n`);
  lines.push(`    public static let cardColor:     Color   = sm.color`);
  lines.push(`    public static let cardRadius:    CGFloat = sm.radius`);
  lines.push(`    public static let cardX:         CGFloat = sm.x`);
  lines.push(`    public static let cardY:         CGFloat = sm.y`);
  lines.push(`    public static let elevatedColor:  Color   = md.color`);
  lines.push(`    public static let elevatedRadius: CGFloat = md.radius`);
  lines.push(`    public static let elevatedX:      CGFloat = md.x`);
  lines.push(`    public static let elevatedY:      CGFloat = md.y`);
  lines.push(`    public static let floatingColor:  Color   = lg.color`);
  lines.push(`    public static let floatingRadius: CGFloat = lg.radius`);
  lines.push(`    public static let floatingX:      CGFloat = lg.x`);
  lines.push(`    public static let floatingY:      CGFloat = lg.y`);
  lines.push(`    public static let noneColor:      Color   = none.color`);
  lines.push(`    public static let noneRadius:     CGFloat = none.radius`);
  lines.push(`    public static let noneX:          CGFloat = none.x`);
  lines.push(`    public static let noneY:          CGFloat = none.y`);
  lines.push(`}`);
  lines.push('');

  // Shadow view modifiers
  lines.push(`// MARK: - Shadow ViewModifiers\n`);
  lines.push(`private struct TokenShadowModifier: ViewModifier {`);
  lines.push(`    let token: Shadows.ShadowToken`);
  lines.push(`    func body(content: Content) -> some View {`);
  lines.push(`        content.shadow(color: token.color, radius: token.radius, x: token.x, y: token.y)`);
  lines.push(`    }`);
  lines.push(`}\n`);
  lines.push(`public extension View {`);
  lines.push(`    /// Applies the resting card shadow (sm elevation).`);
  lines.push(`    func cardShadow() -> some View { modifier(TokenShadowModifier(token: Shadows.sm)) }`);
  lines.push(`    /// Applies the elevated / active-state shadow (md elevation).`);
  lines.push(`    func elevatedShadow() -> some View { modifier(TokenShadowModifier(token: Shadows.md)) }`);
  lines.push(`    /// Applies the floating / modal shadow (lg elevation).`);
  lines.push(`    func floatingShadow() -> some View { modifier(TokenShadowModifier(token: Shadows.lg)) }`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  console.log('ReSpeak3 BrandKit — iOS generator');
  console.log('----------------------------------');

  ensureDir(OUTPUT_DIR);

  const colors = readJSON('colors.json');
  const typo   = readJSON('typography.json');
  const layout = readJSON('layout.json');

  write('BrandColors.swift',    generateColors(colors));
  write('BrandTypography.swift', generateTypography(typo));
  write('BrandLayout.swift',    generateLayout(layout));

  console.log('\nDone. Copy files to ReSpeak/Theme/ or run scripts/sync-brand.sh.\n');
}

main();
